---
title: "Curriculum Vitae"
editor: 
  markdown: 
    wrap: sentence
---

(972)378-8514 Dallas, TX

rrynbrandt\@collin.edu

ryan.rynbrandt\@utdallas.edu

# Ryan Rynbrandt

PROFESSOR OF POLITICAL SCIENCE

Objective: Political science professor with 17 years' experience.
I hold a master's degree in political science and am currently pursuing a PhD in public policy and political economy.
Seeking a position at a top-tier university where I can use my expertise in teaching and research to mentor students and contribute to the advancement of knowledge in the field.

## Education

2021-present: University of Texas Dallas PhD Program in Public Policy and Political Economy

2005: University of Michigan, Ann Arbor MA Political Science

Major: American Politics

First Minor: Public Policy and Administration Second Minor: Research Methodology

```         
    1997    Western Michigan University
```

BA International Politics BA Asian Studies Graduated summa cum laude 1996 Nagoya Gakuin University Certificate of Completion, Japanese Studies Program

## Teaching experience

2007-present

Collin College, Plano, TX Professor, Political Science Department • Prepared and taught in-person courses in GOVT 2301, 2302, 2305 and 2306 • Taught online courses via Blackboard and Canvas • Taught accelerated summer courses 2001-2006 University of Michigan, Ann Arbor Graduate Student Instructor, Department of Political Science • Prepared and led discussion sections for introductory and upper-level classes • Prepared and taught own courses 2005 and 2006 Research experience

```         
    2003-2004   Research Assistant University of Michigan, Ann Arbor
```

PI: Richard L. Hall, Ford School of Public Policy, "Lobbying as Legislative Subsidy" • Conducted in-depth interviews with lobbyists and Congressional staffers • Gathered and managed data and background information for case studies • Helped develop and refine survey instruments and interview protocols • Helped supervise undergrad research assistant 2000-2003 Research Assistant University of Michigan, Ann Arbor PI: Daniel Carpenter, Center for Political Studies, Institute for Social Research, "The FDA Project" • Collected and managed data • Helped develop and refine coding protocols and datasets • Supervised three undergraduate research assistants

## Publications and Presentations

2022

2019

2017

2015

```         
Books
```

Practicing Texas Politics 18th Edition, Cengage Publishers (Lyle Brown, Joyce Langenegger, Sonia Garcia, Robert Biles, Ryan Rynbrandt, Veronica Vega Reyna and Juan Carlos Huerta)

Practicing Texas Politics Enhanced 17th Edition, Cengage Publishers (Lyle Brown, Joyce Langenegger, Sonia Garcia, Robert Biles, Ryan Rynbrandt, Veronica Vega Reyna and Juan Carlos Huerta)

Practicing Texas Politics 2017-2018 Edition, Cengage Publishers (Lyle Brown, Joyce Langenegger, Sonia Garcia, Robert Biles, Ryan Rynbrandt, Veronica Vega Reyna and Juan Carlos Huerta)

Practicing Texas Politics 2015-2016 Edition, Cengage Publishers (Lyle Brown, Joyce Langenegger, Sonia Garcia, Robert Biles, Ryan Rynbrandt and Veronica Vega Reyna)

2010

2020

2017

2016

2014

2005

2004

### Journal Publications

Daniel Carpenter, Susan Moffitt, Colin Moore, Ryan Rynbrandt, Ian Yohai and Evan James Zucker, "Early Entrant Protection in Approval Regulation: Theory and Evidence from FDA Drug Review," Journal of Law, Economics and Organization, 26 (2) Fall 2010

### Conference papers

Ryan Rynbrandt, "Well-being in Democratic Politics, Policy and Governance," World Summit on Social Sciences and Humanities, Assam, India

Ryan Rynbrandt, "Happiness in America," Western Political Science Association Annual Meeting, Vancouver, BC, CA

Ryan Rynbrandt, "The Pursuit of Happiness," Western Political Science Association Annual Meeting, San Diego, CA

Ryan Rynbrandt and Joyce Langeneggar, "It's All Connected...At the Intersection of Evolving Technologies and the World of Texas Politics," Texas Community College Teachers Association Annual Meeting, San Antonio, TX

Ryan Rynbrandt, "We Make the Rules: Policymakers in Executive Agencies," Midwest Political Science Association Annual Meeting, Chicago, IL

Ryan Rynbrandt, "Unelected Legislators: Who Controls the Rulemakers?," Western Political Science Association Annual Meeting, Portland, OR

## Honors and awards

```         
    2020
```

2018 Awarded Collin College/UTD Scholarship

Awarded Special Recognition Inspirational Teaching Certificate, Collin Collegte

```         
    2013
```

2012

2009

2004

2004

2004

2003

1999

1997

1997

1997

1992

1992 Honored with establishment of second Ryan Rynbrandt Engaged Faculty Scholarship

Selected as Director of Collin College Honors Institute

Honored with establishment of Ryan Rynbrandt Engaged Faculty Scholarship

Gerald R. Ford Dissertation Fellowship and Research Grant

University of Michigan Outstanding Student Instructor Award, Rackham Graduate School

University of Michigan Political Science Department Thesis Grant Award

John F. Kingdon Award for Outstanding Graduate Student Teaching

University of Michigan Regent's Fellowship

Western Michigan University Presidential Scholar (selected by faculty as top political science student)

D.C. Schilling Award in Political Science, Western Michigan University

Excellence in Japanese Award, Western Michigan University Department of Languages and Linguistics

University Excellence Award, Western Michigan University

Member Lee Honors College / Political Science Honors Department, Western Michigan University
